/* Richtpreise Discounter-Niveau, Stand: September 2026. Keine tagesaktuellen Preise. */
window.SHOP_ITEMS=[
['kartoffeln','Kartoffeln','Obst & Gemüse',2000,'g',2.79,''],
['suesskartoffeln','Süßkartoffeln','Obst & Gemüse',500,'g',1.79,''],
['zwiebeln','Zwiebeln','Obst & Gemüse',1000,'g',1.29,''],
['lauch','Lauch','Obst & Gemüse',500,'g',1.49,''],
['karotten','Karotten','Obst & Gemüse',1000,'g',1.29,''],
['paprika_bunt','Paprika bunt','Obst & Gemüse',3,'Stk',1.99,''],
['spitzpaprika','Spitzpaprika','Obst & Gemüse',500,'g',1.99,''],
['tomaten','Tomaten','Obst & Gemüse',500,'g',1.79,''],
['kirschtomaten','Kirschtomaten','Obst & Gemüse',500,'g',1.99,''],
['salatgurke','Salatgurke','Obst & Gemüse',1,'Stk',0.79,''],
['snackgurken','Snackgurken','Obst & Gemüse',500,'g',1.79,''],
['zucchini','Zucchini','Obst & Gemüse',500,'g',1.49,''],
['aubergine','Aubergine','Obst & Gemüse',1,'Stk',1.09,''],
['brokkoli','Brokkoli','Obst & Gemüse',500,'g',1.49,''],
['blumenkohl','Blumenkohl','Obst & Gemüse',1,'Stk',1.49,''],
['rosenkohl','Rosenkohl','Obst & Gemüse',500,'g',1.99,''],
['weisskohl','Weißkohl','Obst & Gemüse',1000,'g',0.99,''],
['rotkohl','Rotkohl','Obst & Gemüse',1000,'g',1.29,''],
['spitzkohl','Spitzkohl','Obst & Gemüse',1,'Stk',1.29,''],
['hokkaido_kuerbis','Hokkaido-Kürbis','Obst & Gemüse',1,'Stk',1.79,''],
['butternut_kuerbis','Butternut-Kürbis','Obst & Gemüse',1,'Stk',1.99,''],
['fenchel','Fenchel','Obst & Gemüse',1,'Stk',1.29,''],
['knollensellerie','Knollensellerie','Obst & Gemüse',1,'Stk',1.49,''],
['staudensellerie','Staudensellerie','Obst & Gemüse',1,'Stk',1.29,''],
['kohlrabi','Kohlrabi','Obst & Gemüse',1,'Stk',0.89,''],
['rote_bete_gekocht','Rote Bete gekocht','Obst & Gemüse',500,'g',1.29,''],
['gruener_spargel','Grüner Spargel','Obst & Gemüse',500,'g',3.99,''],
['weisser_spargel','Weißer Spargel','Obst & Gemüse',500,'g',5.99,''],
['champignons','Champignons','Obst & Gemüse',250,'g',1.49,''],
['ingwer','Ingwer','Obst & Gemüse',100,'g',0.89,''],
['knoblauch','Knoblauch','Obst & Gemüse',1,'Stk',0.69,''],
['fruehlingszwiebeln','Frühlingszwiebeln','Obst & Gemüse',1,'Stk',0.89,''],
['eisbergsalat','Eisbergsalat','Obst & Gemüse',1,'Stk',0.99,''],
['romanasalat','Romanasalat','Obst & Gemüse',2,'Stk',1.49,''],
['salatmix','Salatmix','Obst & Gemüse',200,'g',1.29,''],
['rucola','Rucola','Obst & Gemüse',100,'g',0.99,''],
['feldsalat','Feldsalat','Obst & Gemüse',100,'g',1.49,''],
['babyspinat','Babyspinat','Obst & Gemüse',200,'g',1.29,''],
['radieschen','Radieschen','Obst & Gemüse',1,'Stk',0.89,''],
['pak_choi','Pak Choi','Obst & Gemüse',1,'Stk',1.29,''],
['maiskolben','Maiskolben','Obst & Gemüse',2,'Stk',1.49,''],
['gruene_bohnen','Grüne Bohnen','Obst & Gemüse',500,'g',1.99,''],
['petersilie','Petersilie','Obst & Gemüse',1,'Stk',1.29,''],
['basilikum','Basilikum','Obst & Gemüse',1,'Stk',1.29,''],
['schnittlauch','Schnittlauch','Obst & Gemüse',1,'Stk',1.29,''],
['dill','Dill','Obst & Gemüse',1,'Stk',1.29,''],
['koriander','Koriander','Obst & Gemüse',1,'Stk',1.29,''],
['minze','Minze','Obst & Gemüse',1,'Stk',1.29,''],
['rosmarin','Rosmarin','Obst & Gemüse',1,'Stk',1.29,''],
['thymian','Thymian','Obst & Gemüse',1,'Stk',1.29,''],
['aepfel','Äpfel','Obst & Gemüse',1000,'g',2.29,''],
['birnen','Birnen','Obst & Gemüse',1000,'g',2.49,''],
['bananen','Bananen','Obst & Gemüse',1000,'g',1.39,''],
['orangen','Orangen','Obst & Gemüse',2000,'g',2.99,''],
['mandarinen','Mandarinen','Obst & Gemüse',750,'g',1.99,''],
['zitrone','Zitrone','Obst & Gemüse',1,'Stk',0.39,''],
['limette','Limette','Obst & Gemüse',1,'Stk',0.39,''],
['grapefruit','Grapefruit','Obst & Gemüse',1,'Stk',0.79,''],
['weintrauben','Weintrauben','Obst & Gemüse',500,'g',2.49,''],
['erdbeeren','Erdbeeren','Obst & Gemüse',500,'g',2.99,''],
['himbeeren','Himbeeren','Obst & Gemüse',125,'g',1.99,''],
['heidelbeeren','Heidelbeeren','Obst & Gemüse',125,'g',1.99,''],
['kiwi','Kiwi','Obst & Gemüse',4,'Stk',1.49,''],
['mango','Mango','Obst & Gemüse',1,'Stk',1.29,''],
['ananas','Ananas','Obst & Gemüse',1,'Stk',1.79,''],
['wassermelone','Wassermelone','Obst & Gemüse',1,'Stk',3.99,''],
['pflaumen','Pflaumen','Obst & Gemüse',500,'g',1.99,''],
['pfirsiche','Pfirsiche','Obst & Gemüse',500,'g',2.49,''],
['kirschen','Kirschen','Obst & Gemüse',500,'g',3.99,''],
['avocado','Avocado','Obst & Gemüse',2,'Stk',1.79,''],
['vollmilch','Vollmilch','Milch & Eier',1000,'ml',1.15,'d'],
['fettarme_milch','Fettarme Milch','Milch & Eier',1000,'ml',1.05,'d'],
['h_milch','H-Milch','Milch & Eier',1000,'ml',1.09,'d'],
['laktosefreie_milch','Laktosefreie Milch','Milch & Eier',1000,'ml',1.35,''],
['haferdrink','Haferdrink','Milch & Eier',1000,'ml',1.29,''],
['sojadrink','Sojadrink','Milch & Eier',1000,'ml',1.19,''],
['mandeldrink','Mandeldrink','Milch & Eier',1000,'ml',1.49,'n'],
['reisdrink','Reisdrink','Milch & Eier',1000,'ml',1.39,''],
['buttermilch','Buttermilch','Milch & Eier',500,'ml',0.79,'d'],
['kefir','Kefir','Milch & Eier',500,'ml',0.99,'d'],
['naturjoghurt','Naturjoghurt','Milch & Eier',500,'g',0.85,'d'],
['griechischer_joghurt','Griechischer Joghurt','Milch & Eier',500,'g',1.79,'d'],
['fruchtjoghurt','Fruchtjoghurt','Milch & Eier',150,'g',0.35,'du'],
['laktosefreier_joghurt','Laktosefreier Joghurt','Milch & Eier',500,'g',1.29,''],
['sojajoghurt','Sojajoghurt','Milch & Eier',500,'g',1.49,''],
['skyr','Skyr','Milch & Eier',450,'g',1.49,'d'],
['magerquark','Magerquark','Milch & Eier',500,'g',1.05,'d'],
['speisequark_40','Speisequark 40 %','Milch & Eier',500,'g',1.15,'d'],
['frischkaese_natur','Frischkäse natur','Milch & Eier',200,'g',0.99,'d'],
['frischkaese_kraeuter','Frischkäse Kräuter','Milch & Eier',200,'g',1.09,'d'],
['schmand','Schmand','Milch & Eier',200,'g',0.85,'d'],
['creme_fraiche','Crème fraîche','Milch & Eier',200,'g',0.99,'d'],
['schlagsahne','Schlagsahne','Milch & Eier',200,'ml',0.99,'d'],
['kochsahne','Kochsahne','Milch & Eier',200,'ml',0.85,'d'],
['mascarpone','Mascarpone','Milch & Eier',250,'g',1.39,'d'],
['ricotta','Ricotta','Milch & Eier',250,'g',1.19,'d'],
['butter','Butter','Milch & Eier',250,'g',1.99,'d'],
['margarine','Margarine','Milch & Eier',250,'g',1.09,'u'],
['gouda_scheiben','Gouda Scheiben','Milch & Eier',300,'g',1.99,'d'],
['gouda_am_stueck','Gouda am Stück','Milch & Eier',400,'g',2.99,'d'],
['edamer_scheiben','Edamer Scheiben','Milch & Eier',300,'g',1.99,'d'],
['emmentaler_scheiben','Emmentaler Scheiben','Milch & Eier',200,'g',1.99,'d'],
['mozzarella','Mozzarella','Milch & Eier',125,'g',0.69,'d'],
['geriebener_mozzarella','Geriebener Mozzarella','Milch & Eier',200,'g',1.49,'d'],
['feta','Feta','Milch & Eier',200,'g',1.59,'d'],
['halloumi','Halloumi','Milch & Eier',200,'g',2.19,'d'],
['parmesan_gerieben','Parmesan gerieben','Milch & Eier',100,'g',1.49,'d'],
['reibekaese','Reibekäse','Milch & Eier',200,'g',1.69,'d'],
['camembert','Camembert','Milch & Eier',250,'g',1.49,'d'],
['schmelzkaese','Schmelzkäse','Milch & Eier',200,'g',1.09,'du'],
['veganer_kaese','Veganer Käse','Milch & Eier',200,'g',1.99,'u'],
['eier','Eier','Milch & Eier',10,'Stk',2.79,'e'],
['bio_eier','Bio-Eier','Milch & Eier',10,'Stk',3.99,'e'],
['vanillepudding','Vanillepudding','Milch & Eier',500,'g',1.29,'du'],
['schokopudding','Schokopudding','Milch & Eier',4,'Stk',1.09,'du'],
['haehnchenbrustfilet','Hähnchenbrustfilet','Fleisch & Fisch',500,'g',4.79,'m'],
['haehnchenschenkel','Hähnchenschenkel','Fleisch & Fisch',1000,'g',4.19,'m'],
['haehnchen_ganz','Hähnchen ganz','Fleisch & Fisch',1200,'g',3.99,'m'],
['haehnchengeschnetzeltes','Hähnchengeschnetzeltes','Fleisch & Fisch',400,'g',3.79,'m'],
['putenbrust','Putenbrust','Fleisch & Fisch',500,'g',5.49,'m'],
['hackfleisch_gemischt','Hackfleisch gemischt','Fleisch & Fisch',500,'g',3.49,'m'],
['rinderhack','Rinderhack','Fleisch & Fisch',500,'g',4.99,'m'],
['schweineschnitzel','Schweineschnitzel','Fleisch & Fisch',500,'g',3.99,'m'],
['schweinenacken','Schweinenacken','Fleisch & Fisch',500,'g',3.49,'m'],
['schweinegeschnetzeltes','Schweinegeschnetzeltes','Fleisch & Fisch',400,'g',3.49,'m'],
['schweinekotelett','Schweinekotelett','Fleisch & Fisch',500,'g',3.49,'m'],
['rindergulasch','Rindergulasch','Fleisch & Fisch',500,'g',5.99,'m'],
['rumpsteak','Rumpsteak','Fleisch & Fisch',250,'g',5.49,'m'],
['bratwurst','Bratwurst','Fleisch & Fisch',300,'g',2.19,'mu'],
['wiener_wuerstchen','Wiener Würstchen','Fleisch & Fisch',200,'g',1.79,'mu'],
['kochschinken','Kochschinken','Fleisch & Fisch',150,'g',1.29,'mu'],
['rohschinken','Rohschinken','Fleisch & Fisch',100,'g',1.99,'m'],
['salami','Salami','Fleisch & Fisch',100,'g',1.19,'mu'],
['leberwurst','Leberwurst','Fleisch & Fisch',125,'g',1.19,'mu'],
['fleischwurst','Fleischwurst','Fleisch & Fisch',200,'g',1.69,'mu'],
['gefluegelaufschnitt','Geflügelaufschnitt','Fleisch & Fisch',100,'g',0.99,'mu'],
['speckwuerfel','Speckwürfel','Fleisch & Fisch',200,'g',1.49,'m'],
['bacon','Bacon','Fleisch & Fisch',150,'g',1.69,'m'],
['lachsfilet','Lachsfilet','Fleisch & Fisch',250,'g',3.99,'f'],
['raeucherlachs','Räucherlachs','Fleisch & Fisch',100,'g',2.49,'f'],
['forelle','Forelle','Fleisch & Fisch',250,'g',2.99,'f'],
['seelachsfilet','Seelachsfilet','Fleisch & Fisch',400,'g',2.99,'f'],
['thunfisch_in_wasser','Thunfisch in Wasser','Fleisch & Fisch',185,'g',1.29,'f'],
['thunfisch_in_oel','Thunfisch in Öl','Fleisch & Fisch',185,'g',1.29,'f'],
['sardinen','Sardinen','Fleisch & Fisch',120,'g',1.29,'f'],
['garnelen_gekocht','Garnelen gekocht','Fleisch & Fisch',150,'g',2.99,'f'],
['fischstaebchen','Fischstäbchen','Fleisch & Fisch',300,'g',2.19,'fgu'],
['tofu_natur','Tofu natur','Fleisch & Fisch',400,'g',1.99,''],
['raeuchertofu','Räuchertofu','Fleisch & Fisch',200,'g',1.79,''],
['tempeh','Tempeh','Fleisch & Fisch',200,'g',2.29,''],
['seitan','Seitan','Fleisch & Fisch',200,'g',2.49,'g'],
['vegetarische_wuerstchen','Vegetarische Würstchen','Fleisch & Fisch',200,'g',1.99,'gu'],
['vegane_hack_alternative','Vegane Hack-Alternative','Fleisch & Fisch',275,'g',2.49,'gu'],
['vollkornbrot','Vollkornbrot','Brot & Backwaren',500,'g',1.29,'g'],
['mischbrot','Mischbrot','Brot & Backwaren',750,'g',1.59,'g'],
['roggenbrot','Roggenbrot','Brot & Backwaren',500,'g',1.49,'g'],
['dinkelbrot','Dinkelbrot','Brot & Backwaren',500,'g',1.79,'g'],
['toastbrot','Toastbrot','Brot & Backwaren',500,'g',0.99,'gu'],
['vollkorntoast','Vollkorntoast','Brot & Backwaren',500,'g',1.09,'gu'],
['broetchen','Brötchen','Brot & Backwaren',6,'Stk',1.09,'g'],
['vollkornbroetchen','Vollkornbrötchen','Brot & Backwaren',6,'Stk',1.29,'g'],
['hamburgerbroetchen','Hamburgerbrötchen','Brot & Backwaren',4,'Stk',1.19,'gu'],
['baguette','Baguette','Brot & Backwaren',1,'Stk',0.79,'g'],
['wraps','Wraps','Brot & Backwaren',6,'Stk',1.49,'gu'],
['maistortillas','Maistortillas','Brot & Backwaren',8,'Stk',1.79,''],
['fladenbrot','Fladenbrot','Brot & Backwaren',1,'Stk',1.29,'g'],
['pita_brot','Pita-Brot','Brot & Backwaren',6,'Stk',1.29,'g'],
['laugenbroetchen','Laugenbrötchen','Brot & Backwaren',4,'Stk',1.29,'g'],
['laugenbrezeln','Laugenbrezeln','Brot & Backwaren',4,'Stk',1.29,'g'],
['croissants','Croissants','Brot & Backwaren',4,'Stk',1.29,'gdu'],
['knaeckebrot','Knäckebrot','Brot & Backwaren',250,'g',1.09,'g'],
['zwieback','Zwieback','Brot & Backwaren',225,'g',1.29,'g'],
['trockenhefe','Trockenhefe','Brot & Backwaren',3,'Stk',0.79,''],
['backpulver','Backpulver','Brot & Backwaren',6,'Stk',0.79,''],
['semmelbroesel','Semmelbrösel','Brot & Backwaren',400,'g',0.79,'g'],
['spaghetti','Spaghetti','Vorrat',500,'g',0.99,'g'],
['penne','Penne','Vorrat',500,'g',0.99,'g'],
['fusilli','Fusilli','Vorrat',500,'g',0.99,'g'],
['spirelli','Spirelli','Vorrat',500,'g',0.99,'g'],
['bandnudeln','Bandnudeln','Vorrat',500,'g',1.29,'ge'],
['lasagneplatten','Lasagneplatten','Vorrat',250,'g',1.19,'g'],
['spaetzle','Spätzle','Vorrat',500,'g',1.49,'ge'],
['vollkornnudeln','Vollkornnudeln','Vorrat',500,'g',1.09,'g'],
['glutenfreie_nudeln','Glutenfreie Nudeln','Vorrat',500,'g',1.99,''],
['reisnudeln','Reisnudeln','Vorrat',250,'g',1.29,''],
['gnocchi','Gnocchi','Vorrat',500,'g',1.49,'g'],
['langkornreis','Langkornreis','Vorrat',1000,'g',1.99,''],
['basmatireis','Basmatireis','Vorrat',1000,'g',2.49,''],
['vollkornreis','Vollkornreis','Vorrat',1000,'g',2.29,''],
['risottoreis','Risottoreis','Vorrat',500,'g',1.99,''],
['milchreis','Milchreis','Vorrat',500,'g',1.29,''],
['couscous','Couscous','Vorrat',500,'g',1.49,'g'],
['bulgur','Bulgur','Vorrat',500,'g',1.39,'g'],
['quinoa','Quinoa','Vorrat',500,'g',3.49,''],
['hirse','Hirse','Vorrat',500,'g',1.99,''],
['polenta','Polenta','Vorrat',500,'g',1.29,''],
['griess','Grieß','Vorrat',500,'g',1.09,'g'],
['haferflocken','Haferflocken','Vorrat',500,'g',0.89,'g'],
['fruechtemuesli','Früchtemüsli','Vorrat',750,'g',1.99,'g'],
['cornflakes','Cornflakes','Vorrat',375,'g',1.19,'gu'],
['weizenmehl','Weizenmehl','Vorrat',1000,'g',0.89,'g'],
['vollkornmehl','Vollkornmehl','Vorrat',1000,'g',1.29,'g'],
['rote_linsen','Rote Linsen','Vorrat',500,'g',1.99,''],
['braune_linsen','Braune Linsen','Vorrat',500,'g',1.79,''],
['gruene_linsen','Grüne Linsen','Vorrat',500,'g',2.29,''],
['kichererbsen','Kichererbsen','Vorrat',400,'g',0.79,''],
['kidneybohnen','Kidneybohnen','Vorrat',400,'g',0.75,''],
['weisse_bohnen','Weiße Bohnen','Vorrat',400,'g',0.75,''],
['schwarze_bohnen','Schwarze Bohnen','Vorrat',400,'g',0.89,''],
['mais_dose','Mais Dose','Vorrat',285,'g',0.69,''],
['erbsen_dose','Erbsen Dose','Vorrat',400,'g',0.79,''],
['gehackte_tomaten','Gehackte Tomaten','Vorrat',400,'g',0.69,''],
['passierte_tomaten','Passierte Tomaten','Vorrat',500,'g',0.89,''],
['passata','Passata','Vorrat',700,'g',1.19,''],
['tomatenmark','Tomatenmark','Vorrat',200,'g',0.89,''],
['kokosmilch','Kokosmilch','Vorrat',400,'ml',1.29,''],
['sardellenfilets','Sardellenfilets','Vorrat',50,'g',1.49,'f'],
['pesto_genovese','Pesto Genovese','Vorrat',190,'g',1.49,'dnu'],
['pesto_rosso','Pesto Rosso','Vorrat',190,'g',1.49,'dnu'],
['tomatensauce','Tomatensauce','Vorrat',400,'g',1.29,'u'],
['sauce_bolognese','Sauce Bolognese','Vorrat',400,'g',1.49,'mu'],
['ketchup','Ketchup','Vorrat',500,'ml',1.29,'u'],
['mayonnaise','Mayonnaise','Vorrat',500,'ml',1.39,'eu'],
['remoulade','Remoulade','Vorrat',250,'g',1.29,'eu'],
['sojasauce','Sojasauce','Vorrat',250,'ml',1.29,'g'],
['sweet_chili_sauce','Sweet-Chili-Sauce','Vorrat',300,'ml',1.29,'u'],
['rote_currypaste','Rote Currypaste','Vorrat',110,'g',1.29,''],
['gruene_currypaste','Grüne Currypaste','Vorrat',110,'g',1.29,''],
['harissa','Harissa','Vorrat',140,'g',1.29,''],
['erdnussmus','Erdnussmus','Vorrat',350,'g',1.99,'n'],
['erdbeermarmelade','Erdbeermarmelade','Vorrat',450,'g',1.29,''],
['nuss_nougat_creme','Nuss-Nougat-Creme','Vorrat',400,'g',1.79,'ndu'],
['honig','Honig','Vorrat',500,'g',3.49,'e'],
['ahornsirup','Ahornsirup','Vorrat',250,'ml',3.99,''],
['walnuesse','Walnüsse','Vorrat',200,'g',2.49,'n'],
['mandeln','Mandeln','Vorrat',200,'g',2.49,'n'],
['cashewkerne','Cashewkerne','Vorrat',200,'g',2.99,'n'],
['erdnuesse_geroestet','Erdnüsse geröstet','Vorrat',250,'g',1.49,'n'],
['sonnenblumenkerne','Sonnenblumenkerne','Vorrat',250,'g',1.19,''],
['kuerbiskerne','Kürbiskerne','Vorrat',250,'g',1.99,''],
['chiasamen','Chiasamen','Vorrat',250,'g',2.49,''],
['leinsamen','Leinsamen','Vorrat',250,'g',1.29,''],
['rosinen','Rosinen','Vorrat',250,'g',1.29,''],
['datteln','Datteln','Vorrat',250,'g',1.99,''],
['gruene_oliven','Grüne Oliven','Vorrat',350,'g',1.29,''],
['schwarze_oliven','Schwarze Oliven','Vorrat',350,'g',1.29,''],
['kapern','Kapern','Vorrat',100,'g',0.99,''],
['gewuerzgurken','Gewürzgurken','Vorrat',670,'g',1.29,''],
['sauerkraut','Sauerkraut','Vorrat',810,'g',0.99,''],
['rotkohl_im_glas','Rotkohl im Glas','Vorrat',720,'g',1.29,''],
['maiskoelbchen','Maiskölbchen','Vorrat',425,'g',1.29,''],
['tortilla_chips','Tortilla-Chips','Vorrat',200,'g',1.29,'u'],
['taco_schalen','Taco-Schalen','Vorrat',12,'Stk',1.79,'u'],
['semmelknoedel','Semmelknödel','Vorrat',6,'Stk',1.29,'gu'],
['kartoffelpueree','Kartoffelpüree','Vorrat',250,'g',1.29,'du'],
['farfalle','Farfalle','Vorrat',500,'g',0.99,'g'],
['makkaroni','Makkaroni','Vorrat',500,'g',0.99,'g'],
['suppennudeln','Suppennudeln','Vorrat',250,'g',0.79,'g'],
['jasminreis','Jasminreis','Vorrat',1000,'g',2.29,''],
['haferflocken_kernig','Haferflocken kernig','Vorrat',500,'g',0.89,'g'],
['dinkelmehl','Dinkelmehl','Vorrat',1000,'g',1.49,'g'],
['ananas_dose','Ananas Dose','Vorrat',340,'g',1.09,''],
['pfirsiche_dose','Pfirsiche Dose','Vorrat',425,'g',1.29,''],
['haselnuesse','Haselnüsse','Vorrat',200,'g',2.29,'n'],
['pinienkerne','Pinienkerne','Vorrat',100,'g',3.49,'n'],
['aprikosenmarmelade','Aprikosenmarmelade','Vorrat',450,'g',1.29,''],
['cornichons','Cornichons','Vorrat',300,'g',1.09,''],
['tahini','Tahini','Vorrat',250,'g',2.99,''],
['bbq_sauce','BBQ-Sauce','Vorrat',300,'ml',1.29,'u'],
['tomatensuppe_dose','Tomatensuppe Dose','Vorrat',400,'ml',1.49,'u'],
['erbsensuppe_dose','Erbsensuppe Dose','Vorrat',800,'g',1.99,'mu'],
['ravioli_dose','Ravioli Dose','Vorrat',800,'g',1.79,'mgu'],
['puddingpulver_vanille','Puddingpulver Vanille','Vorrat',3,'Stk',0.79,'u'],
['blattspinat','Blattspinat','Tiefkühl',450,'g',1.29,''],
['rahmspinat','Rahmspinat','Tiefkühl',450,'g',1.39,'d'],
['erbsen_tiefgekuehlt','Erbsen tiefgekühlt','Tiefkühl',750,'g',1.39,''],
['gemuesemischung','Gemüsemischung','Tiefkühl',750,'g',1.59,''],
['buttergemuese','Buttergemüse','Tiefkühl',750,'g',1.59,'d'],
['brokkoli_tiefgekuehlt','Brokkoli tiefgekühlt','Tiefkühl',600,'g',1.49,''],
['blumenkohl_tiefgekuehlt','Blumenkohl tiefgekühlt','Tiefkühl',600,'g',1.49,''],
['gemuesepfanne','Gemüsepfanne','Tiefkühl',750,'g',1.99,''],
['beerenmischung','Beerenmischung','Tiefkühl',500,'g',2.99,''],
['himbeeren_tiefgekuehlt','Himbeeren tiefgekühlt','Tiefkühl',300,'g',2.49,''],
['erdbeeren_tiefgekuehlt','Erdbeeren tiefgekühlt','Tiefkühl',500,'g',2.49,''],
['pommes_frites','Pommes frites','Tiefkühl',1000,'g',1.89,'u'],
['kroketten','Kroketten','Tiefkühl',750,'g',1.79,'u'],
['kartoffelecken','Kartoffelecken','Tiefkühl',750,'g',1.79,'u'],
['kartoffelroesti','Kartoffelrösti','Tiefkühl',500,'g',1.79,'u'],
['pizza_salami','Pizza Salami','Tiefkühl',350,'g',1.49,'gdmu'],
['pizza_margherita','Pizza Margherita','Tiefkühl',300,'g',1.29,'gdu'],
['pangasiusfilet','Pangasiusfilet','Tiefkühl',500,'g',3.49,'f'],
['lachsfilet_tiefgekuehlt','Lachsfilet tiefgekühlt','Tiefkühl',500,'g',4.99,'f'],
['riesengarnelen_roh','Riesengarnelen roh','Tiefkühl',250,'g',4.49,'f'],
['haehnchen_nuggets','Hähnchen-Nuggets','Tiefkühl',500,'g',2.99,'mgu'],
['vanilleeis','Vanilleeis','Tiefkühl',1000,'ml',1.79,'du'],
['schokoeis','Schokoeis','Tiefkühl',1000,'ml',1.79,'du'],
['blaetterteig','Blätterteig','Tiefkühl',275,'g',1.29,'gu'],
['pizzateig','Pizzateig','Tiefkühl',400,'g',1.29,'gu'],
['mineralwasser_still','Mineralwasser still','Getränke',1500,'ml',0.24,''],
['mineralwasser_classic','Mineralwasser Classic','Getränke',1500,'ml',0.24,''],
['sprudel_zitrone','Sprudel Zitrone','Getränke',1500,'ml',0.39,'u'],
['apfelsaft','Apfelsaft','Getränke',1000,'ml',1.19,''],
['orangensaft','Orangensaft','Getränke',1000,'ml',1.49,''],
['multivitaminsaft','Multivitaminsaft','Getränke',1000,'ml',1.29,''],
['apfelschorle','Apfelschorle','Getränke',1500,'ml',0.59,''],
['cola','Cola','Getränke',1500,'ml',0.79,'u'],
['cola_zero','Cola Zero','Getränke',1500,'ml',0.79,'u'],
['zitronenlimonade','Zitronenlimonade','Getränke',1500,'ml',0.69,'u'],
['orangenlimonade','Orangenlimonade','Getränke',1500,'ml',0.69,'u'],
['eistee_pfirsich','Eistee Pfirsich','Getränke',1500,'ml',0.79,'u'],
['energy_drink','Energy Drink','Getränke',250,'ml',0.59,'u'],
['kaffee_gemahlen','Kaffee gemahlen','Getränke',500,'g',4.49,''],
['kaffeebohnen','Kaffeebohnen','Getränke',1000,'g',9.99,''],
['loeskaffee','Löskaffee','Getränke',200,'g',4.99,''],
['schwarztee','Schwarztee','Getränke',50,'Stk',1.49,''],
['kraeutertee','Kräutertee','Getränke',20,'Stk',0.99,''],
['gruener_tee','Grüner Tee','Getränke',20,'Stk',1.29,''],
['trinkschokolade','Trinkschokolade','Getränke',400,'g',1.99,'du'],
['pils','Pils','Getränke',500,'ml',0.69,'g'],
['weizenbier','Weizenbier','Getränke',500,'ml',0.79,'g'],
['rotwein','Rotwein','Getränke',750,'ml',3.99,''],
['weisswein','Weißwein','Getränke',750,'ml',3.99,''],
['sekt','Sekt','Getränke',750,'ml',3.49,''],
['vollmilchschokolade','Vollmilchschokolade','Snacks & Süßes',100,'g',0.69,'du'],
['zartbitterschokolade','Zartbitterschokolade','Snacks & Süßes',100,'g',0.79,'u'],
['nussschokolade','Nussschokolade','Snacks & Süßes',100,'g',0.79,'dnu'],
['schokoriegel','Schokoriegel','Snacks & Süßes',5,'Stk',1.99,'dnu'],
['butterkekse','Butterkekse','Snacks & Süßes',200,'g',0.99,'gdu'],
['doppelkekse','Doppelkekse','Snacks & Süßes',250,'g',1.19,'gdu'],
['haferkekse','Haferkekse','Snacks & Süßes',250,'g',1.29,'gdu'],
['salzcracker','Salzcracker','Snacks & Süßes',200,'g',0.99,'gu'],
['kartoffelchips_paprika','Kartoffelchips Paprika','Snacks & Süßes',175,'g',1.29,'u'],
['kartoffelchips_salz','Kartoffelchips Salz','Snacks & Süßes',175,'g',1.29,'u'],
['salzstangen','Salzstangen','Snacks & Süßes',250,'g',0.99,'gu'],
['erdnussflips','Erdnussflips','Snacks & Süßes',250,'g',1.19,'nu'],
['gummibaerchen','Gummibärchen','Snacks & Süßes',200,'g',0.89,'eu'],
['saure_fruchtgummis','Saure Fruchtgummis','Snacks & Süßes',200,'g',0.99,'eu'],
['lakritz','Lakritz','Snacks & Süßes',200,'g',1.19,'gu'],
['muesliriegel','Müsliriegel','Snacks & Süßes',6,'Stk',1.29,'gnu'],
['fruchtriegel','Fruchtriegel','Snacks & Süßes',5,'Stk',1.49,'u'],
['nussmix','Nussmix','Snacks & Süßes',200,'g',1.99,'n'],
['popcorn_mikrowelle','Popcorn Mikrowelle','Snacks & Süßes',3,'Stk',1.19,'du'],
['reiswaffeln','Reiswaffeln','Snacks & Süßes',100,'g',0.99,''],
['reiswaffeln_schoko','Reiswaffeln Schoko','Snacks & Süßes',100,'g',1.49,'du'],
['schokopralinen','Schokopralinen','Snacks & Süßes',200,'g',2.49,'dnu'],
['marzipan','Marzipan','Snacks & Süßes',200,'g',1.79,'n'],
['schokokuesse','Schokoküsse','Snacks & Süßes',6,'Stk',1.29,'eu'],
['speisesalz','Speisesalz','Gewürze & Basics',500,'g',0.39,'x'],
['pfeffer_schwarz','Pfeffer schwarz','Gewürze & Basics',50,'g',1.09,'x'],
['zucker','Zucker','Gewürze & Basics',1000,'g',1.19,'x'],
['puderzucker','Puderzucker','Gewürze & Basics',250,'g',0.89,'x'],
['brauner_zucker','Brauner Zucker','Gewürze & Basics',500,'g',1.49,'x'],
['vanillezucker','Vanillezucker','Gewürze & Basics',5,'Stk',0.59,'x'],
['sonnenblumenoel','Sonnenblumenöl','Gewürze & Basics',1000,'ml',1.99,'x'],
['rapsoel','Rapsöl','Gewürze & Basics',1000,'ml',2.29,'x'],
['olivenoel','Olivenöl','Gewürze & Basics',500,'ml',4.99,'x'],
['balsamico_essig','Balsamico-Essig','Gewürze & Basics',500,'ml',1.49,'x'],
['apfelessig','Apfelessig','Gewürze & Basics',750,'ml',0.99,'x'],
['branntweinessig','Branntweinessig','Gewürze & Basics',1000,'ml',0.69,'x'],
['senf_mittelscharf','Senf mittelscharf','Gewürze & Basics',200,'ml',0.55,'x'],
['dijon_senf','Dijon-Senf','Gewürze & Basics',200,'ml',0.79,'x'],
['gemuesebruehe_wuerfel','Gemüsebrühe Würfel','Gewürze & Basics',12,'Stk',0.99,'xu'],
['huehnerbruehe_wuerfel','Hühnerbrühe Würfel','Gewürze & Basics',12,'Stk',1.19,'xmu'],
['gemuesebruehe_pulver','Gemüsebrühe Pulver','Gewürze & Basics',250,'g',1.49,'xu'],
['paprika_edelsuess','Paprika edelsüß','Gewürze & Basics',40,'g',0.89,'x'],
['paprika_geraeuchert','Paprika geräuchert','Gewürze & Basics',40,'g',1.09,'x'],
['curry','Curry','Gewürze & Basics',40,'g',0.99,'x'],
['kurkuma','Kurkuma','Gewürze & Basics',35,'g',1.09,'x'],
['kreuzkuemmel','Kreuzkümmel','Gewürze & Basics',35,'g',1.09,'x'],
['zimt_gemahlen','Zimt gemahlen','Gewürze & Basics',35,'g',1.09,'x'],
['muskatnuss_gemahlen','Muskatnuss gemahlen','Gewürze & Basics',30,'g',1.19,'x'],
['oregano','Oregano','Gewürze & Basics',15,'g',0.79,'x'],
['thymian_getrocknet','Thymian getrocknet','Gewürze & Basics',15,'g',0.79,'x'],
['basilikum_getrocknet','Basilikum getrocknet','Gewürze & Basics',15,'g',0.79,'x'],
['rosmarin_getrocknet','Rosmarin getrocknet','Gewürze & Basics',20,'g',0.79,'x'],
['chiliflocken','Chiliflocken','Gewürze & Basics',30,'g',0.99,'x'],
['ras_el_hanout','Ras el Hanout','Gewürze & Basics',35,'g',1.39,'x'],
['garam_masala','Garam Masala','Gewürze & Basics',35,'g',1.39,'x'],
['lorbeerblaetter','Lorbeerblätter','Gewürze & Basics',8,'g',0.79,'x'],
['backkakao','Backkakao','Gewürze & Basics',100,'g',1.39,'x'],
['speisestaerke','Speisestärke','Gewürze & Basics',400,'g',0.89,'x'],
['zitronensaft','Zitronensaft','Gewürze & Basics',200,'ml',0.79,'x'],
['worcestersauce','Worcestersauce','Gewürze & Basics',150,'ml',1.19,'xf'],
['kraeuter_der_provence','Kräuter der Provence','Gewürze & Basics',15,'g',0.89,'x'],
['knoblauchgranulat','Knoblauchgranulat','Gewürze & Basics',45,'g',1.09,'x'],
['zwiebelpulver','Zwiebelpulver','Gewürze & Basics',40,'g',1.09,'x'],
['koriander_gemahlen','Koriander gemahlen','Gewürze & Basics',30,'g',1.09,'x'],
['ingwer_gemahlen','Ingwer gemahlen','Gewürze & Basics',30,'g',1.09,'x'],
['grillgewuerz','Grillgewürz','Gewürze & Basics',40,'g',0.99,'x'],
['kuechenrolle','Küchenrolle','Haushalt',4,'Stk',1.49,''],
['toilettenpapier','Toilettenpapier','Haushalt',10,'Stk',2.29,''],
['spuelmittel','Spülmittel','Haushalt',1,'Stk',0.79,''],
['spuelmaschinentabs','Spülmaschinentabs','Haushalt',30,'Stk',3.99,''],
['muellbeutel','Müllbeutel','Haushalt',20,'Stk',1.29,''],
['waschmittel','Waschmittel','Haushalt',1,'Stk',4.49,''],
['zahnpasta','Zahnpasta','Haushalt',1,'Stk',0.79,''],
['duschgel','Duschgel','Haushalt',1,'Stk',0.99,''],
['shampoo','Shampoo','Haushalt',1,'Stk',0.99,''],
['handseife','Handseife','Haushalt',1,'Stk',0.99,''],
['alufolie','Alufolie','Haushalt',1,'Stk',1.49,''],
['backpapier','Backpapier','Haushalt',1,'Stk',1.29,''],
['frischhaltefolie','Frischhaltefolie','Haushalt',1,'Stk',1.29,''],
['gefrierbeutel','Gefrierbeutel','Haushalt',30,'Stk',1.29,''],
['taschentuecher','Taschentücher','Haushalt',30,'Stk',1.29,''],
];
